[base]
package = super_mario_land
env_name = super_mario_land

[train]
total_timesteps = 15_000_000
; total_timesteps = 3_400_000

; num_envs = 16
; num_workers = 16
; batch_size = 4096
; minibatch_size = 1024
; compile = False
; checkpoint_interval = 200


; update_epochs = 2
; learning_rate = 1e-4
; anneal_lr = True
; gae_lambda = 0.95
; norm_adv = True
; clip_coef = 0.1
; clip_vloss = True
; vf_coef = 0.5
; vf_clip_coef = 0.1
; max_grad_norm = 0.5
; ent_coef = 0.01
; gamma = 0.98
; target_kl = None



anneal_lr= True
batch_size= 4096
bptt_horizon= 4
checkpoint_interval= 200
clip_coef= 0.23708411518170974
clip_vloss= True
compile= True
compile_mode= reduce-overhead
cpu_offload= False
data_dir= experiments
device= cuda
ent_coef= 0.009462238091472371
gae_lambda= 0.8275754283451554
gamma= 0.9393924390436624
learning_rate= 0.0005556737478394448
max_grad_norm= 0.3729556202888489
minibatch_size= 1024
norm_adv= True
num_envs= 16
num_workers= 16
seed= 1
torch_deterministic= True
update_epochs= 2
vf_clip_coef= 0.05626419586316986
vf_coef= 0.6036866362849499
zero_copy= True


[sweep]
method = bayes
name = sweep
project = mario_carbs

[sweep.metric]
goal = maximize
name = environment/episode_return

[sweep.parameters.train.parameters.total_timesteps]
distribution = uniform
min = 2_500_000
max = 10_000_000

[sweep.parameters.train.parameters.learning_rate]
distribution = log_uniform_values
min = 1e-5
max = 1e-1

[sweep.parameters.train.parameters.gamma]
distribution = uniform
min = 0.0
max = 1.0

[sweep.parameters.train.parameters.gae_lambda]
distribution = uniform
min = 0.0
max = 1.0

[sweep.parameters.train.parameters.update_epochs]
distribution = int_uniform
min = 1
max = 4

[sweep.parameters.train.parameters.clip_coef]
distribution = uniform
min = 0.0
max = 1.0

[sweep.parameters.train.parameters.vf_coef]
distribution = uniform
min = 0.0
max = 1.0

[sweep.parameters.train.parameters.vf_clip_coef]
distribution = uniform
min = 0.0
max = 1.0

[sweep.parameters.train.parameters.max_grad_norm]
distribution = uniform
min = 0.0
max = 10.0

[sweep.parameters.train.parameters.ent_coef]
distribution = log_uniform_values
min = 1e-5
max = 3e-2

[sweep.parameters.train.parameters.bptt_horizon]
values = [1, 2, 4, 8, 16]

[sweep.parameters.train.parameters.batch_size]
distribution = uniform
min = 2048
max = 16384

[sweep.parameters.train.parameters.minibatch_size]
distribution = uniform
min = 1024
max = 8192